### ISSUE TITLE
cannot access properly

### ISSUE THREAD

**Issue by wcx0209** [Arslan-Mehmood1/Machine-learning-pipeline-deployment-using-Docker-and-FastAPI#1]
![image](https://github.com/Arslan-Mehmood1/Machine-learning-pipeline-deployment-using-Docker-and-FastAPI/assets/122070161/0045ec18-6a00-4cce-8792-7fc128c22791)

![image](https://github.com/Arslan-Mehmood1/Machine-learning-pipeline-deployment-using-Docker-and-FastAPI/assets/122070161/467d92da-4217-462c-8ec6-a913b6e9f3e4)

**Comment by Arslan-Mehmood1** [comment]
Hi @wcx0209 , no root '/' endpoint is implemented in the api, only '/predict' is implemented.
